"""Repair only degenerate ``MaterialUV`` corners on the new rigid hardware.

This is an in-memory, callable Blender helper.  It is deliberately narrower
than the general material-finish passes: the target set is the six wheel axle
supports, the authored bow deck, and the authored bow rail/post set.  Hull,
sail, cloth, cabin, and retained source objects are never searched or edited.

The tube authoring recipe gives the body circumference/depth faces a valid
longitudinal UV, but its two end-cap n-gons inherit a constant longitudinal
coordinate.  The bow deck has the same issue on its two existing end faces.
For a polygon containing one or more degenerate non-zero-area triangles, this
helper projects only that containing polygon onto the two axes orthogonal to
its dominant world normal.  (An n-gon cap can share loops between fan
triangles, so repairing the containing cap is the smallest possible UV write.)
The projection uses a ten-metre repeat so wood grain remains at the scene's
authored physical scale.  Existing non-degenerate tube body faces are left
byte-for-byte at their current ``MaterialUV`` values.

Some of the authored hardware still points a normal or base-color texture at
``SourceUV``.  For a target slot with that real binding, the helper makes a
stable, target-only material copy that shares the original image/PBR nodes and
changes only that copy's UVMap nodes to ``MaterialUV``.  The original material
and every non-target slot remain untouched; pure-color materials are not
copied.

Image Texture nodes whose Vector input is unconnected use Blender's implicit
active render UV.  Every selected target mesh therefore also makes
``MaterialUV`` both the active UV layer and the active render layer.  This is
what makes an unconnected DeckTeak base-color texture export as glTF
``TEXCOORD_1`` instead of silently falling back to ``UVMap``/``TEXCOORD_0``;
the report records those implicit bindings explicitly.

``SourceUV``, vertices, edges, polygon winding/topology, and shape-key data are
captured before the write and asserted unchanged afterwards.  The public
``refine_fixed_hardware_uv(scene)`` (also exported as ``apply``) returns a
JSON-serialisable before/after audit and never saves, exports, or writes a
file.  Importing this module performs no work.
"""

from __future__ import annotations

import math
from typing import Any

import bpy
from mathutils import Vector


# The six names are the only wheel objects permitted in this pass.  They are
# generated by refine_voyage_wheel_rear_orientation.py and carry both ownership
# flags below.  Keep this explicit: a prefix search would accidentally include
# the retained cloth, spokes, or wheel roots.
WHEEL_TARGETS = {
    "SV3_Wheel_Port_SocketElbow": "rigid-wheel-socket-elbow",
    "SV3_Wheel_Port_OutboardBrace": "rigid-outboard-wheel-brace",
    "SV3_Wheel_Port_AxleConnector": "rigid-wheel-axle",
    "SV3_Wheel_Starboard_SocketElbow": "rigid-wheel-socket-elbow",
    "SV3_Wheel_Starboard_OutboardBrace": "rigid-outboard-wheel-brace",
    "SV3_Wheel_Starboard_AxleConnector": "rigid-wheel-axle",
}

# The current bow route has six stations per side: six posts and five rail
# segments per side, plus one transverse tip rail.  Keep these names explicit
# as part of the ownership boundary instead of repairing every SV3_Bow* mesh.
BOW_POST_TARGETS = {
    f"SV3_BowPlatform_Post_{side}_{station}"
    for side in (-1, 1)
    for station in range(6)
}
BOW_RAIL_TARGETS = {
    f"SV3_BowPlatform_Rail_{side}_{station}"
    for side in (-1, 1)
    for station in range(1, 6)
}
BOW_TARGETS = BOW_POST_TARGETS | BOW_RAIL_TARGETS | {"SV3_BowPlatform_TipRail"}
BOW_DECK = "SV3_BowPlatform_Deck"

TARGET_NAMES = frozenset(WHEEL_TARGETS) | frozenset(BOW_TARGETS) | {BOW_DECK}

MATERIAL_UV = "MaterialUV"
SOURCE_UV = "SourceUV"
UV_METERS_PER_REPEAT = 10.0
GEOMETRY_AREA_EPSILON = 1.0e-4
UV_DENSITY_EPSILON = 1.0e-7
SIGNATURE_DIGITS = 9
MATERIAL_COPY_PREFIX = "SV3_FixedHardwareUV__"
MATERIAL_COPY_SOURCE_PROP = "fixed_hardware_uv_source_material"
MATERIAL_COPY_LAYER_PROP = "fixed_hardware_uv_layer"
MATERIAL_COPY_MARKER_PROP = "fixed_hardware_uv_material_copy"


def _rounded(value: Any) -> float:
    return round(float(value), SIGNATURE_DIGITS)


def _vector_signature(vector: Any) -> tuple[float, float, float]:
    return tuple(_rounded(component) for component in vector)


def _geometry_signature(mesh: Any) -> tuple[Any, ...]:
    """Capture all mesh identity touched by a UV-only operation."""

    shape_keys = mesh.shape_keys
    key_signature = ()
    if shape_keys is not None:
        key_signature = tuple(
            (
                str(key.name),
                tuple(_vector_signature(item.co) for item in key.data),
            )
            for key in shape_keys.key_blocks
        )
    return (
        tuple(_vector_signature(vertex.co) for vertex in mesh.vertices),
        tuple(tuple(int(index) for index in edge.vertices) for edge in mesh.edges),
        tuple(
            (
                tuple(int(index) for index in polygon.vertices),
                bool(polygon.use_smooth),
            )
            for polygon in mesh.polygons
        ),
        key_signature,
    )


def _uv_signature(layer: Any) -> tuple[Any, ...] | None:
    if layer is None:
        return None
    return tuple((_rounded(item.uv.x), _rounded(item.uv.y)) for item in layer.data)


def _image_texture_nodes(material: Any) -> list[Any]:
    """Return actual image texture nodes; a pure Principled color is ignored."""

    if material is None or not getattr(material, "use_nodes", False):
        return []
    tree = getattr(material, "node_tree", None)
    if tree is None:
        return []
    return [
        node
        for node in tree.nodes
        if node.type == "TEX_IMAGE" and getattr(node, "image", None) is not None
    ]


def _upstream_uv_maps(socket: Any, visited: set[int] | None = None) -> set[str]:
    """Follow a texture Vector input through Mapping nodes to UVMap nodes."""

    if socket is None:
        return set()
    visited = set() if visited is None else visited
    names: set[str] = set()
    for link in socket.links:
        node = link.from_node
        marker = id(node)
        if marker in visited:
            continue
        visited.add(marker)
        if node.type == "UVMAP" and node.uv_map:
            names.add(str(node.uv_map))
        for input_socket in node.inputs:
            names.update(_upstream_uv_maps(input_socket, visited))
    return names


def _source_uv_texture_bindings(material: Any) -> list[dict[str, Any]]:
    """Describe textured inputs that actually receive a SourceUV node."""

    bindings = []
    for texture in _image_texture_nodes(material):
        vector = texture.inputs.get("Vector")
        uv_maps = sorted(_upstream_uv_maps(vector))
        if SOURCE_UV not in uv_maps:
            continue
        bindings.append(
            {
                "texture_node": str(texture.name),
                "image": str(texture.image.name),
                "uv_maps": uv_maps,
            }
        )
    return bindings


def _implicit_default_uv_texture_bindings(material: Any) -> list[dict[str, Any]]:
    """Describe image textures using Blender's implicit active-render UV.

    A texture with no Vector link has no explicit ``UVMap`` node for the
    exporter to inspect.  Blender samples the mesh's active render UV in that
    case, so this helper records the selection instead of pretending the
    material is untextured.  Generated/Object mappings are intentionally not
    classified as implicit UV mappings.
    """

    bindings = []
    for texture in _image_texture_nodes(material):
        vector = texture.inputs.get("Vector")
        if vector is None or vector.links:
            continue
        bindings.append(
            {
                "texture_node": str(texture.name),
                "image": str(texture.image.name),
                "vector_source": "unconnected",
                "uv_selection": "active_render",
                "default_uv": MATERIAL_UV,
            }
        )
    return bindings


def _activate_material_uv(objects: list[Any]) -> list[dict[str, Any]]:
    """Make MaterialUV the explicit and implicit UV choice on target meshes."""

    reports = []
    for obj in objects:
        layers = obj.data.uv_layers
        layer = layers.get(MATERIAL_UV)
        if layer is None or len(layer.data) != len(obj.data.loops):
            raise RuntimeError(
                f"fixed hardware UV: {obj.name} {MATERIAL_UV} is missing or malformed"
            )
        before_active = str(layers.active.name) if layers.active is not None else None
        before_render = next(
            (str(candidate.name) for candidate in layers if candidate.active_render),
            None,
        )
        # Blender keeps one active_render layer per mesh.  Setting both fields
        # is intentional: explicit UV users see MaterialUV and unconnected
        # Image Texture nodes follow the same layer during glTF export.
        layers.active = layer
        layer.active_render = True
        reports.append(
            {
                "object": str(obj.name),
                "active_uv_before": before_active,
                "active_render_uv_before": before_render,
                "active_uv_after": str(layers.active.name),
                "active_render_uv_after": str(
                    next(candidate.name for candidate in layers if candidate.active_render)
                ),
                "implicit_default_uv": MATERIAL_UV,
                "implicit_default_uv_policy": "unconnected Image Texture Vector uses active_render",
            }
        )
    return reports


def _material_copy_for(source: Any) -> Any:
    """Return or create the stable isolated copy for one source material."""

    if str(source.name).startswith(MATERIAL_COPY_PREFIX):
        if source.get(MATERIAL_COPY_MARKER_PROP) and source.get(MATERIAL_COPY_LAYER_PROP) == MATERIAL_UV:
            return source
        raise RuntimeError(
            f"fixed hardware UV: reserved material name has invalid metadata: {source.name}"
        )

    copy_name = MATERIAL_COPY_PREFIX + str(source.name)
    target = bpy.data.materials.get(copy_name)
    if target is None:
        target = next(
            (
                material
                for material in bpy.data.materials
                if material.get(MATERIAL_COPY_SOURCE_PROP) == source.name
            ),
            None,
        )
    if target is None:
        target = source.copy()
        target.name = copy_name
    else:
        if target.get(MATERIAL_COPY_SOURCE_PROP) not in {None, source.name}:
            raise RuntimeError(
                f"fixed hardware UV: stable material copy belongs to another source: {target.name}"
            )

    target[MATERIAL_COPY_MARKER_PROP] = True
    target[MATERIAL_COPY_SOURCE_PROP] = str(source.name)
    target[MATERIAL_COPY_LAYER_PROP] = MATERIAL_UV
    return target


def _switch_copy_uv_nodes(material: Any) -> list[str]:
    """Change only SourceUV UVMAP nodes in an isolated copy."""

    changed = []
    if not getattr(material, "use_nodes", False) or material.node_tree is None:
        return changed
    for node in material.node_tree.nodes:
        if node.type == "UVMAP" and node.uv_map == SOURCE_UV:
            changed.append(str(node.name))
            node.uv_map = MATERIAL_UV
    return changed


def _prepare_target_materials(objects: list[Any]) -> tuple[dict[str, list[dict[str, Any]]], list[dict[str, Any]]]:
    """Isolate actual SourceUV texture bindings on target material slots."""

    by_object: dict[str, list[dict[str, Any]]] = {}
    replacements: list[dict[str, Any]] = []
    for obj in objects:
        mesh = obj.data
        for slot_index, source in enumerate(mesh.materials):
            if source is None:
                continue
            # A second call sees the already isolated material.  Keep its
            # identity and metadata, without making ``__...__...`` copies.
            if source.get(MATERIAL_COPY_MARKER_PROP):
                target = source
                source_name = str(source.get(MATERIAL_COPY_SOURCE_PROP) or source.name)
                source_bindings = []
                implicit_bindings = _implicit_default_uv_texture_bindings(target)
                changed_nodes = _switch_copy_uv_nodes(target)
                target_uv_nodes = sorted(
                    str(node.name)
                    for node in target.node_tree.nodes
                    if node.type == "UVMAP" and node.uv_map == MATERIAL_UV
                ) if target.use_nodes and target.node_tree else []
                slot_changed = False
            else:
                source_bindings = _source_uv_texture_bindings(source)
                implicit_bindings = _implicit_default_uv_texture_bindings(source)
                if not source_bindings and not implicit_bindings:
                    # Includes pure-color materials and materials whose
                    # textures already use an explicit non-SourceUV mapping.
                    continue
                if source_bindings:
                    target = _material_copy_for(source)
                    changed_nodes = _switch_copy_uv_nodes(target)
                    target_uv_nodes = sorted(
                        str(node.name)
                        for node in target.node_tree.nodes
                        if node.type == "UVMAP" and node.uv_map == MATERIAL_UV
                    ) if target.use_nodes and target.node_tree else []
                    slot_changed = source != target
                    mesh.materials[slot_index] = target
                else:
                    # An unconnected Image Texture already follows the mesh's
                    # active_render UV. The target mesh is switched in
                    # _activate_material_uv; no material copy is necessary.
                    target = source
                    changed_nodes = []
                    target_uv_nodes = []
                    slot_changed = False
                source_name = str(source.name)

            report = {
                "object": str(obj.name),
                "slot": int(slot_index),
                "source_material": source_name,
                "target_material": str(target.name),
                "slot_replaced": bool(slot_changed),
                "source_uv": SOURCE_UV,
                "target_uv": MATERIAL_UV,
                "source_uv_texture_bindings": source_bindings,
                "implicit_default_uv_texture_bindings": implicit_bindings,
                "changed_uvmap_nodes": changed_nodes,
                "target_material_uvmap_nodes": target_uv_nodes,
                "shared_texture_images_and_pbr": True,
                "pure_color_copied": False,
                "stable_copy_name": str(target.name).startswith(MATERIAL_COPY_PREFIX),
                "implicit_default_uv_selected": bool(implicit_bindings),
            }
            by_object.setdefault(str(obj.name), []).append(report)
            replacements.append(report)
    return by_object, replacements


def _uv_area(layer: Any, triangle: Any) -> float:
    uv = [layer.data[loop_index].uv for loop_index in triangle.loops]
    first = uv[1] - uv[0]
    second = uv[2] - uv[0]
    return abs(float(first.x * second.y - first.y * second.x))


def _world_normal(obj: Any, polygon: Any) -> Vector:
    """Return a normalized world-space polygon normal, including scale."""

    try:
        normal = obj.matrix_world.to_3x3().inverted_safe().transposed() @ polygon.normal
    except (AttributeError, TypeError, ValueError):
        normal = Vector(polygon.normal)
    if normal.length <= 1.0e-12:
        return Vector((0.0, 0.0, 1.0))
    return normal.normalized()


def _projection_axes(normal: Vector) -> tuple[int, tuple[int, int]]:
    dominant = max(range(3), key=lambda axis: abs(float(normal[axis])))
    pairs = ((1, 2), (0, 2), (0, 1))
    return dominant, pairs[dominant]


def _polygon_world_point(obj: Any, mesh: Any, loop_index: int) -> Vector:
    vertex_index = mesh.loops[loop_index].vertex_index
    return obj.matrix_world @ mesh.vertices[vertex_index].co


def _triangle_stats(obj: Any) -> dict[str, Any]:
    """Measure only non-zero-area triangles, matching the GLB checker."""

    mesh = obj.data
    layer = mesh.uv_layers.get(MATERIAL_UV)
    if layer is None:
        raise RuntimeError(f"fixed hardware UV: {obj.name} has no {MATERIAL_UV} layer")
    if len(layer.data) != len(mesh.loops):
        raise RuntimeError(f"fixed hardware UV: {obj.name} {MATERIAL_UV} length mismatch")

    mesh.calc_loop_triangles()
    triangles = 0
    degenerate_triangles = 0
    by_polygon: dict[int, dict[str, int]] = {}
    for triangle in mesh.loop_triangles:
        points = [_polygon_world_point(obj, mesh, index) for index in triangle.loops]
        geometry_area = (points[1] - points[0]).cross(points[2] - points[0]).length
        if geometry_area < GEOMETRY_AREA_EPSILON:
            continue
        triangles += 1
        polygon_index = int(triangle.polygon_index)
        bucket = by_polygon.setdefault(polygon_index, {"triangles": 0, "degenerate": 0})
        bucket["triangles"] += 1
        density = _uv_area(layer, triangle) / geometry_area
        if density <= UV_DENSITY_EPSILON:
            degenerate_triangles += 1
            bucket["degenerate"] += 1

    # UVs are stored per loop, so an n-gon cap's fan triangles can share loops:
    # a few triangles may sit just above the density threshold while its other
    # triangles are truly collapsed.  The smallest safe write is therefore
    # the containing cap polygon, while body polygons remain untouched.
    degenerate_polygons = sorted(
        polygon_index
        for polygon_index, bucket in by_polygon.items()
        if bucket["degenerate"] > 0
    )
    fully_degenerate_polygons = sorted(
        polygon_index
        for polygon_index, bucket in by_polygon.items()
        if bucket["degenerate"] == bucket["triangles"] and bucket["triangles"] > 0
    )
    mixed_polygons = sorted(
        polygon_index
        for polygon_index, bucket in by_polygon.items()
        if 0 < bucket["degenerate"] < bucket["triangles"]
    )
    return {
        "triangles": triangles,
        "degenerate_triangles": degenerate_triangles,
        "degenerate_polygons": degenerate_polygons,
        "fully_degenerate_polygons": fully_degenerate_polygons,
        "mixed_polygons": mixed_polygons,
    }


def _target_kind(obj: Any) -> str | None:
    name = str(obj.name)
    if name in WHEEL_TARGETS:
        return "wheel-axle-support"
    if name == BOW_DECK:
        return "bow-deck"
    if name in BOW_TARGETS:
        return "bow-railing"
    return None


def _validate_ownership(obj: Any, kind: str) -> None:
    if obj.type != "MESH":
        raise RuntimeError(f"fixed hardware UV: {obj.name} is not a mesh")
    if kind == "wheel-axle-support":
        expected = WHEEL_TARGETS[obj.name]
        if not bool(obj.get("rigid_axle_support")):
            raise RuntimeError(f"fixed hardware UV: {obj.name} lost rigid_axle_support ownership")
        if obj.get("rig_kind") != expected:
            raise RuntimeError(
                f"fixed hardware UV: {obj.name} rig_kind {obj.get('rig_kind')!r} != {expected!r}"
            )
        return
    if kind == "bow-deck":
        if not bool(obj.get("walk_surface")) or not str(obj.get("bow_contract") or ""):
            raise RuntimeError(f"fixed hardware UV: {obj.name} lost walk_surface/bow_contract ownership")
        return
    if obj.get("rig_kind") != "rigid-bow-railing":
        raise RuntimeError(f"fixed hardware UV: {obj.name} lost rigid-bow-railing ownership")


def _project_polygon(obj: Any, polygon: Any, layer: Any) -> dict[str, Any]:
    """Write this one polygon's MaterialUV by dominant-normal projection."""

    normal = _world_normal(obj, polygon)
    dominant, pair = _projection_axes(normal)
    for loop_index in polygon.loop_indices:
        point = _polygon_world_point(obj, obj.data, loop_index)
        layer.data[loop_index].uv = (
            float(point[pair[0]]) / UV_METERS_PER_REPEAT,
            float(point[pair[1]]) / UV_METERS_PER_REPEAT,
        )
    return {
        "polygon": int(polygon.index),
        "dominant_normal_axis": "XYZ"[dominant],
        "projected_axes": "XYZ"[pair[0]] + "XYZ"[pair[1]],
        "world_meters_per_repeat": UV_METERS_PER_REPEAT,
    }


def _repair_object(obj: Any, material_slots: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    mesh = obj.data
    source_layer = mesh.uv_layers.get(SOURCE_UV)
    material_layer = mesh.uv_layers.get(MATERIAL_UV)
    if source_layer is None or len(source_layer.data) != len(mesh.loops):
        raise RuntimeError(f"fixed hardware UV: {obj.name} SourceUV is missing or malformed")
    if material_layer is None or len(material_layer.data) != len(mesh.loops):
        raise RuntimeError(f"fixed hardware UV: {obj.name} MaterialUV is missing or malformed")

    geometry_before = _geometry_signature(mesh)
    source_before = _uv_signature(source_layer)
    material_before = _uv_signature(material_layer)
    before = _triangle_stats(obj)
    repaired = []
    for polygon_index in before["degenerate_polygons"]:
        repaired.append(_project_polygon(obj, mesh.polygons[polygon_index], material_layer))

    mesh.update()
    after = _triangle_stats(obj)
    geometry_after = _geometry_signature(mesh)
    source_after = _uv_signature(source_layer)
    material_after = _uv_signature(material_layer)
    if geometry_before != geometry_after:
        raise RuntimeError(f"fixed hardware UV: geometry/topology changed for {obj.name}")
    if source_before != source_after:
        raise RuntimeError(f"fixed hardware UV: SourceUV changed for {obj.name}")
    repaired_indices = {entry["polygon"] for entry in repaired}
    unresolved = repaired_indices.intersection(after["degenerate_polygons"])
    if unresolved:
        raise RuntimeError(f"fixed hardware UV: unresolved polygons on {obj.name}: {sorted(unresolved)}")

    return {
        "object": obj.name,
        "ownership": _target_kind(obj),
        "material_uv_layer": MATERIAL_UV,
        "source_uv_layer": SOURCE_UV,
        "material_slots": material_slots or [],
        "before": before,
        "after": after,
        "repaired_polygons": repaired,
        "material_uv_changed": material_before != material_after,
        "geometry_preserved": geometry_before == geometry_after,
        "topology_preserved": geometry_before[1:3] == geometry_after[1:3],
        "source_uv_preserved": source_before == source_after,
    }


def _objects_for_scene(scene: Any) -> tuple[list[Any], list[str]]:
    if scene is None:
        raise ValueError("fixed hardware UV: a Blender scene is required")
    selected = []
    missing = []
    for name in sorted(TARGET_NAMES):
        obj = scene.objects.get(name)
        if obj is None:
            missing.append(name)
            continue
        kind = _target_kind(obj)
        if kind is None:
            raise RuntimeError(f"fixed hardware UV: unexpected target selector for {name}")
        _validate_ownership(obj, kind)
        selected.append(obj)
    return selected, missing


def refine_fixed_hardware_uv(scene: Any = None) -> dict[str, Any]:
    """Repair the bounded fixed-hardware UV set in memory and return an audit."""

    scene = scene or bpy.context.scene
    objects, missing = _objects_for_scene(scene)
    active_uv_reports = _activate_material_uv(objects)
    material_slots_by_object, material_replacements = _prepare_target_materials(objects)
    reports = [
        _repair_object(obj, material_slots_by_object.get(str(obj.name)))
        for obj in objects
    ]
    return {
        "schema": "maple.sky-voyage.fixed-hardware-material-uv-report.v1",
        "target_names": sorted(TARGET_NAMES),
        "processed_objects": [report["object"] for report in reports],
        "missing_targets": missing,
        "target_count": len(reports),
        "world_meters_per_repeat": UV_METERS_PER_REPEAT,
        "active_material_uv": active_uv_reports,
        "material_slot_replacements": material_replacements,
        "material_copy_prefix": MATERIAL_COPY_PREFIX,
        "repair_scope": {
            "uv_layer": MATERIAL_UV,
            "material_slots": "target-only isolated copies for actual SourceUV texture bindings; implicit textures use target MaterialUV active_render",
            "implicit_default_uv": MATERIAL_UV,
            "implicit_default_uv_policy": "unconnected Image Texture Vector uses active_render",
            "source_uv_preserved": True,
            "geometry_preserved": True,
            "topology_preserved": True,
            "non_degenerate_tube_body_preserved": True,
            "projection": "dominant world normal; orthogonal plane; ten metre repeat",
            "ownership": "explicit names plus rigid_axle_support/rig_kind or walk_surface/bow_contract",
        },
        "reports": reports,
        "geometry_changed": False,
        "source_uv_changed": False,
        "export_performed": False,
        "save_performed": False,
    }


# Native export recipes conventionally call ``apply(scene)``.  Keep the alias
# explicit without adding a second implementation or any import-time work.
apply = refine_fixed_hardware_uv


if __name__ == "__main__":
    import json

    print(json.dumps(refine_fixed_hardware_uv(), ensure_ascii=False, indent=2))
