import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
import * as Three from 'three';
const rules = JSON.parse(fs.readFileSync(new URL('../../../../shared/town-lamps.json', import.meta.url), 'utf8'));
const loads = [];
// CPU Three objects exercise the real pool and lifecycle; bitmap loading is the one browser boundary.
const T = { ...Three, TextureLoader: class { load(url, ready) { const texture = new Three.Texture(); loads.push({ url, ready, texture }); return texture; } } };
const source = fs.readFileSync(new URL('./town-lamps.ts', import.meta.url), 'utf8');
const js = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext } }).outputText.replace(/^import .*;\r?\n/gm, '').replace(/^export /gm, '');
const { TownLamps, lampIlluminanceAt } = new Function('T', 'rules', 'resolveAssetUrl', `${js};return {TownLamps,lampIlluminanceAt};`)(T, rules, url => url);
assert.equal(rules.sourceClass, 'P');
assert.equal(rules.art.lantern.sourceClass, 'T');
const png = fs.readFileSync(new URL(`../../../public-tms273${rules.art.lantern.url}`, import.meta.url));
assert.equal(png.readUInt32BE(16), rules.art.lantern.width); assert.equal(png.readUInt32BE(20), rules.art.lantern.height);
const scene = new Three.Scene(), lamps = new TownLamps(scene);
const self = { id: 'self', kind: 'player', point: [0, 0, 0], facing: 1, townLamp: { tier: 1, issued: true, revision: 1 } };
const npcs = Array.from({ length: 45 }, (_, i) => ({ id: `npc-${i}`, kind: 'npc', point: [i * .2, 0, 1], townLamp: { tier: 1, kind: 'lantern' } }));
const ordinary = Array.from({ length: 80 }, (_, i) => ({ id: `ordinary-${i}`, kind: 'monster', point: [0, 0, .1], templateId: i ? 'Fire-lie' : 'Energy-lie' }));
let samples = lamps.update([self, ...ordinary, ...npcs], 'self', 0);
assert.equal(samples.length, 8); assert.equal(samples[0].id, 'self'); assert.equal(lamps.root.children.length, 32);
assert.ok(samples.every(sample => !sample.id.startsWith('ordinary')), 'names cannot invent emissive identity');
assert.equal(scene.children.filter(light => light.isPointLight).length, 8);
assert.equal(lamps.pool.filter(light => light.castShadow).length, 2);
assert.equal(samples[0].intensity, 8); assert.equal(samples[0].distance, 3); assert.equal(samples[0].decay, 2);
for (let i = 0; i < samples.length; i++) { const light = lamps.pool[i], sample = samples[i]; assert.deepEqual(sample.position, light.position.toArray()); assert.deepEqual(sample.color, light.color.toArray()); assert.equal(sample.intensity, light.intensity); assert.equal(sample.distance, light.distance); }
loads[0].ready(loads[0].texture); lamps.update([self, ...npcs], 'self', .1);
assert.ok(lamps.holders.get('self').art.visible); assert.equal(lamps.holders.get('self').flame.visible, false);
lamps.setQuality(false); samples = lamps.update([self, ...npcs], 'self', .2); assert.equal(samples.length, 6); assert.equal(lamps.pool.filter(light => light.castShadow).length, 0);
samples = lamps.update([{ ...self, townLamp: { tier: 0, issued: true, revision: 2 } }, ...npcs], 'self', .3);
assert.ok(!samples.some(sample => sample.id === 'self')); assert.ok(!lamps.holders.has('self'), 'discard removes the prop as well as its light');
const high = { ...self, townLamp: { tier: 3, issued: true, revision: 3 } };
samples = lamps.update([high], 'self', .4); assert.equal(samples[0].intensity, 35); assert.equal(samples[0].distance, 7);
const at = samples[0].position, near = lampIlluminanceAt([at[0] + 1, at[1], at[2]], samples), farther = lampIlluminanceAt([at[0] + 2, at[1], at[2]], samples);
assert.ok(near[0] > farther[0] * 3, 'inverse-square attenuation and cutoff stay in the sample chain');
assert.deepEqual(lampIlluminanceAt([at[0] + 7, at[1], at[2]], samples), [0, 0, 0]);
assert.deepEqual(lampIlluminanceAt([at[0] + 1, at[1], at[2]], samples, () => true), [0, 0, 0], 'an actual blocker stops paper-doll direct light');
const explicit = { id: 'fire', kind: 'monster', point: [1, 0, 0], emissive: { color: [1, .4, .1], intensityCandela: 12, rangeMetres: 4 } };
samples = lamps.update([self, explicit, ...ordinary], 'self', .5); const fire = samples.find(sample => sample.id === 'fire'); assert.equal(fire.intensity, 12); assert.deepEqual(fire.color, [1, .4, .1]);
assert.equal(lamps.holders.get('fire').group.children.length, 0, 'an emissive monster does not get a handheld lamp prop');
lamps.update([self, { ...explicit, emissive: { ...explicit.emissive, intensityCandela: NaN } }], 'self', .6); assert.ok(!lamps.holders.has('fire'));
assert.deepEqual(lamps.update([self], 'self', .7, { strength: 0 }), []); assert.ok(lamps.pool.every(light => light.intensity === 0));
samples = lamps.update([self, { ...npcs[0], id: 'far', point: [100, 0, 0] }], 'self', .8); assert.equal(samples.length, 1); assert.equal(lamps.root.children.length, 1);
lamps.destroy(); lamps.destroy(); assert.equal(scene.children.length, 0); assert.deepEqual(lamps.update([self], 'self', 1), []);
const laterScene = new Three.Scene(), later = new TownLamps(laterScene), lateLoad = loads.at(-1); let disposed = 0;
lateLoad.texture.addEventListener('dispose', () => disposed++); later.destroy(); lateLoad.ready(lateLoad.texture);
assert.equal(later.artReady, false); assert.equal(laterScene.children.length, 0); assert.equal(disposed, 2, 'late bitmap delivery is disposed instead of reviving a destroyed view');
console.log('PASS: original lamp bitmap, 32 valid nearby holders, actual 8/6 light pool, bounded shadows, no implicit monster/self light, cd/metre attenuation, blocker and async disposal.');
