import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import ts from 'typescript';

// Exercise the real scene's portal methods without a renderer or live account.
const source = await readFile(new URL('./world.ts', import.meta.url), 'utf8');
const { outputText } = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext } });
const moduleSource = 'const Phaser = { Scene: class {} };\n' + outputText.replace(/^import .*;\r?\n/gm, '');
const { World } = await import(`data:text/javascript;base64,${Buffer.from(moduleSource).toString('base64')}`);
const requests = [];
const statuses = [];
const portal = { name: 'out00', type: 2, x: 100, y: 100, targetMapId: 'next', targetPortalName: 'in00' };
const world = new World({ map: { id: 'birth', portals: [portal] } }, (message, error) => statuses.push({ message, error }), request => requests.push(request));
const player = { id: 'self', hp: 50, action: 'stand', x: 100, y: 100 };
world.loaded = true;
world.snapshot = { selfId: 'self', players: [player] };
world.tryPortal(player, true);
assert.equal(requests.length, 0, 'Walking into a regular portal does not warp');
world.enterPortal();
assert.equal(requests.length, 1, 'Up enters the regular portal');
world.enterPortal();
assert.equal(requests.length, 1, 'Cooldown blocks duplicate requests');
world.portalCooldownUntil = 0;
player.action = 'attack';
world.enterPortal();
player.action = 'stand';
player.hp = 0;
world.enterPortal();
player.hp = 50;
player.x = 300;
world.enterPortal();
assert.equal(requests.length, 1, 'Attacking, dead, and distant players cannot enter');
player.x = 100;
portal.type = 3;
world.tryPortal(player, true);
assert.equal(requests.length, 2, 'Touch portals keep their automatic trigger');
world.portalCooldownUntil = 0;
portal.type = 10;
portal.targetMapId = 'birth';
world.tryPortal(player, true);
assert.equal(requests.length, 2, 'Hidden same-map portals require Up');
world.enterPortal();
assert.equal(requests.length, 3, 'Up enters hidden same-map portals');
assert.equal(requests.at(-1).targetMapId, 'birth');
world.portalCooldownUntil = 0;
world.loaded = false;
world.enterPortal();
assert.equal(requests.length, 3, 'Loading a map cannot enter a portal');
world.receive({ type: 'portalResult', success: false, code: 'out_of_range' });
assert.equal(statuses.at(-1).error, undefined, 'A rejected portal request must not disconnect the game');
console.log('PASS: manual regular portals, touch portals, cooldown and player guards.');
