#!/usr/bin/env python3
"""从 shared/quest-text.json 生成客户端任务日志文案映射 TS（M2 时代产物）。

M3 之后客户端日志文案改为"服务端权威下发"（questList/questUpdate 按玩家
语言直接携带语料文本），客户端不再引用本脚本生成的 quest-text.generated.ts
（该文件已于 M3 删除）。本脚本仅保留作离线语料抽查/回放用途，勿再写回
client/src；如需生成请改 --out 指向证据目录。

只输出"有 zh 或有 log"的任务（en 名称本就由服务端下发，作回退兜底一并带上）。
用法:
  python3 scripts/quest_i18n/gen_quest_log_map.py [--corpus PATH] [--out PATH]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser()
    root = Path(__file__).resolve().parents[2]
    ap.add_argument("--corpus", default=str(root / "shared/quest-text.json"))
    ap.add_argument(
        "--out",
        default=str(root / "client/src/features/quest/quest-text.generated.ts"),
    )
    args = ap.parse_args()

    corpus = json.loads(Path(args.corpus).read_text(encoding="utf-8"))
    lines: list[str] = []
    count = 0
    for qid in sorted(corpus["quests"], key=lambda x: (x.isdigit() is False, int(x) if x.isdigit() else 0)):
        e = corpus["quests"][qid]
        name_zh = e.get("name", {}).get("zh")
        log = e.get("log")
        if not name_zh and not log:
            continue
        parts = []
        nm = {"en": e["name"]["en"]}
        if name_zh:
            nm["zh"] = name_zh
        parts.append(f"name: {json.dumps(nm, ensure_ascii=False)}")
        if log:
            parts.append(f"summary: {json.dumps({'zh': log['zh'], 'en': log['en']}, ensure_ascii=False)}")
        lines.append(f"  {json.dumps(qid)}: {{ {', '.join(parts)} }},")
        count += 1

    header = (
        "/* AUTO-GENERATED by scripts/quest_i18n/gen_quest_log_map.py -- do not edit. */\n"
        "import type { UiLocale } from '../../app/i18n';\n\n"
        "export interface QuestTextEntry {\n"
        "  name?: Partial<Record<UiLocale, string>>;\n"
        "  summary?: Partial<Record<UiLocale, string>>;\n"
        "}\n\n"
        "export const questTextMap: Readonly<Record<string, QuestTextEntry>> = {\n"
    )
    Path(args.out).write_text(header + "\n".join(lines) + "\n};\n", encoding="utf-8")
    print(f"OK  生成 {count} 条 -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
