//! Npc placement, dialogue and shops.
//!
//! The dialogue is a data-driven state machine generated by
//! `scripts/generate_npcs.py` from `P0nk/Cosmic scripts/npc/*.js`.  It is a
//! plain structure plus one resolver, not a script engine: untrusted input can
//! only pick between the transitions an authored node declares.
//!
//! Player-facing text is localized in the gameplay data: every `text` field is
//! either a plain string (legacy English) or a `{ "en": .., "zh": .. }` map.
//! The resolver picks the player's language with English as the fallback and
//! Chinese as the product default, mirroring `quest_text`.

use serde::Deserialize;
use std::collections::BTreeMap;

/// Horizontal/vertical reach used for "talk to the npc you are standing at".
/// Generous on purpose: the rendered maps cover ~1500 px and v83 dialogue
/// triggers work as long as the player is on the same foothold range.
pub const TALK_RANGE_X: f64 = 800.0;
pub const TALK_RANGE_Y: f64 = 600.0;

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)] // func mirrors Npc.wz func; stand frames are client-owned render data.
pub struct NpcTemplate {
    #[serde(alias = "id")]
    pub template_id: String,
    pub name: String,
    #[serde(default)]
    pub func: String,
    #[serde(default)]
    pub shop_id: Option<String>,
    #[serde(default)]
    pub script: Option<DialogueScript>,
    /// Npc.wz stand frames; the client owns rendering, the server only checks
    /// that every placed template carries at least one frame.
    #[serde(default)]
    pub stand: Vec<serde_json::Value>,
}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)] // foothold_id mirrors the WZ spawn metadata; pathing is client-side.
pub struct NpcSpawn {
    #[serde(alias = "spawnId")]
    pub id: String,
    pub template_id: String,
    pub x: f64,
    pub y: f64,
    #[serde(default)]
    pub foothold_id: Option<u64>,
    #[serde(default)]
    pub map_id: String,
    #[serde(default = "default_facing")]
    pub facing: i8,
}

fn default_facing() -> i8 {
    1
}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)] // position mirrors reference shop ordering; sale order is authoritative.
pub struct ShopEntry {
    pub item_id: String,
    pub price: u64,
    #[serde(default)]
    pub position: u32,
}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Shop {
    pub shop_id: String,
    pub npc_id: String,
    #[serde(default)]
    pub items: Vec<ShopEntry>,
}

impl Shop {
    pub fn price(&self, item_id: &str) -> Option<u64> {
        self.items
            .iter()
            .find(|entry| entry.item_id == item_id)
            .map(|entry| entry.price)
    }
}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DialogueScript {
    pub start: String,
    pub nodes: BTreeMap<String, DialogueNode>,
}

/// A player-facing text: either a plain string (legacy, always English) or a
/// per-locale map such as `{"en": .., "zh": ..}`.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize)]
#[serde(untagged)]
pub enum LocalizedText {
    Plain(String),
    PerLang(BTreeMap<String, String>),
}

impl LocalizedText {
    /// Best text for the requested locale: exact locale first, English second,
    /// then the raw string (legacy English) so no authored node can produce a
    /// blank dialogue.
    pub fn pick(&self, lang: &str) -> &str {
        match self {
            Self::Plain(text) => text,
            Self::PerLang(map) => map
                .get(lang)
                .or_else(|| map.get(crate::quest_text::LANG_EN))
                .map(String::as_str)
                .unwrap_or_default(),
        }
    }
}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum DialogueNode {
    Say(SayNode),
    Ask(AskNode),
    Menu(MenuNode),
    Act(ActNode),
    Branch(BranchNode),
}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SayNode {
    pub text: LocalizedText,
    /// `next`, `nextPrev`, `prev` or `ok`, matching the cm.send* the reference
    /// script used and therefore which buttons the client must render.
    pub kind: String,
    pub next: Option<String>,
    pub prev: Option<String>,
}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AskNode {
    pub text: LocalizedText,
    pub yes: String,
    pub no: String,
}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MenuNode {
    pub text: LocalizedText,
    pub options: Vec<MenuOption>,
}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MenuOption {
    pub index: u32,
    pub text: LocalizedText,
    pub next: String,
}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActNode {
    pub kind: String,
    /// Optional continuation after a one-shot action.  Job advancement uses
    /// this to apply the job immediately while still showing the authored
    /// success `say` node to the player.
    #[serde(default)]
    pub next: Option<String>,
    #[serde(default)]
    pub map_id: Option<String>,
    #[serde(default)]
    pub shop_id: Option<String>,
    /// Job advancement fields; set together with `kind` "jobAdvance".
    #[serde(default)]
    pub from_job: Option<u32>,
    #[serde(default)]
    pub job: Option<u32>,
    /// Quest effect fields; set together with `kind` "quest".
    #[serde(default)]
    pub quest_id: Option<String>,
    /// `start` marks the quest active, `complete` finishes it and grants its
    /// configured reward (applied by the world).
    #[serde(default)]
    pub quest_action: Option<String>,
}

/// All present fields must hold; the generator only ever emits single-field
/// conditions today.
#[derive(Clone, Default, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Condition {
    #[serde(default)]
    pub have_item: Option<String>,
    #[serde(default)]
    pub level_at_least: Option<u32>,
    #[serde(default)]
    pub meso_at_least: Option<u64>,
    /// Passes when the account has an `active` row for this quest id.
    #[serde(default)]
    pub quest_active: Option<String>,
    /// Passes when the account has a `completed` row for this quest id.
    #[serde(default)]
    pub quest_completed: Option<String>,
    /// Passes when the account has no row at all for this quest id.
    #[serde(default)]
    pub quest_available: Option<String>,
    /// Passes when the player's current hp is at least this value (used by
    /// completion gates such as quest 1021 "Roger's Apple": hp must be full).
    #[serde(default)]
    pub hp_at_least: Option<u32>,
}

/// Read-only view of the player state a condition may test.
pub struct DialogueContext<'a> {
    pub hp: u32,
    pub level: u32,
    pub mesos: u64,
    pub inventory: &'a [crate::protocol::InventoryItem],
    /// quest id -> "active" | "completed"; absent rows are "available".
    pub quests: &'a BTreeMap<String, String>,
    /// Display language for localized dialogue text ("zh" default, "en" for
    /// the ?lang=en UI).  See quest_text::normalize_lang.
    pub lang: &'a str,
}

#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BranchNode {
    pub cond: Condition,
    pub then: String,
    #[serde(rename = "else")]
    pub otherwise: String,
}

/// A dialogue action the world must apply once, after the client-visible view
/// is produced (the conversation ends after a quest effect, matching the
/// server-driven accept/complete hand-off).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum QuestEffect {
    Start(String),
    Complete(String),
    JobAdvance { from_job: u32, job: u32 },
}

impl Condition {
    fn matches(&self, context: &DialogueContext<'_>) -> bool {
        if let Some(item_id) = self.have_item.as_deref() {
            if !context
                .inventory
                .iter()
                .any(|item| item.item_id == item_id && item.quantity > 0)
            {
                return false;
            }
        }
        if let Some(level) = self.level_at_least {
            if context.level < level {
                return false;
            }
        }
        if let Some(mesos) = self.meso_at_least {
            if context.mesos < mesos {
                return false;
            }
        }
        let quest_status = |quest_id: &str| context.quests.get(quest_id).map(String::as_str);
        if let Some(quest_id) = self.quest_active.as_deref() {
            if quest_status(quest_id) != Some("active") {
                return false;
            }
        }
        if let Some(quest_id) = self.quest_completed.as_deref() {
            if quest_status(quest_id) != Some("completed") {
                return false;
            }
        }
        if let Some(quest_id) = self.quest_available.as_deref() {
            if quest_status(quest_id).is_some() {
                return false;
            }
        }
        if let Some(min_hp) = self.hp_at_least {
            if context.hp < min_hp {
                return false;
            }
        }
        true
    }
}

impl DialogueScript {
    pub fn validate(&self, template_id: &str) -> Result<(), String> {
        if !self.nodes.contains_key(&self.start) {
            return Err(format!("npc {template_id} dialogue start node is missing"));
        }
        for (name, node) in &self.nodes {
            for target in node.targets() {
                if !self.nodes.contains_key(&target) {
                    return Err(format!(
                        "npc {template_id} dialogue node {name} references unknown node {target}"
                    ));
                }
            }
        }
        Ok(())
    }
}

impl DialogueNode {
    fn targets(&self) -> Vec<String> {
        match self {
            Self::Say(say) => [say.next.clone(), say.prev.clone()]
                .into_iter()
                .flatten()
                .collect(),
            Self::Ask(ask) => vec![ask.yes.clone(), ask.no.clone()],
            Self::Menu(menu) => menu
                .options
                .iter()
                .map(|option| option.next.clone())
                .collect(),
            Self::Act(act) => act.next.clone().into_iter().collect(),
            Self::Branch(branch) => vec![branch.then.clone(), branch.otherwise.clone()],
        }
    }
}

/// What the client has to render after one step.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum DialogueView {
    Say {
        text: String,
        kind: String,
        options: Vec<(u32, String)>,
    },
    OpenShop {
        shop_id: String,
    },
    Warp {
        map_id: String,
    },
    End,
}

impl DialogueView {
    pub fn to_json(
        &self,
        request_id: &str,
        npc_id: &str,
        name: &str,
        name_zh: Option<&str>,
    ) -> serde_json::Value {
        let mut value = serde_json::json!({
            "type": "npcResult",
            "requestId": request_id,
            "success": true,
            "code": "",
            "npcId": npc_id,
            "name": name,
        });
        if let Some(name_zh) = name_zh {
            value["nameZh"] = serde_json::Value::String(name_zh.to_owned());
        }
        match self {
            Self::Say {
                text,
                kind,
                options,
            } => {
                value["dialog"] = serde_json::json!({
                    "kind": kind,
                    "text": text,
                    "options": options.iter()
                        .map(|(index, text)| serde_json::json!({"index": index, "text": text}))
                        .collect::<Vec<_>>(),
                });
            }
            Self::OpenShop { shop_id } => {
                value["shop"] = serde_json::json!({ "shopId": shop_id });
            }
            Self::Warp { map_id } => {
                value["warp"] = serde_json::json!({ "mapId": map_id });
            }
            Self::End => {
                value["ended"] = serde_json::Value::Bool(true);
            }
        }
        value
    }
}

/// 阶段一（2026-09-17）：没有原版脚本的 NPC 被点击时的占位对话来源标记。
///
/// 已摆放的 265 个 NPC 模板里只有 30 个带 `script`，其余全部落在「无脚本」分支；
/// 那一条此前只回一个 `ended`，玩家点下去屏幕上什么都不发生。阶段一改为回一段
/// 占位提示，并用这个标记把「占位」与「服务端脚本／职能产生的对话」区分开：
/// 缺省表示这段对话由服务端脚本或职能分发产生，`placeholder` 表示还没有内容。
///
/// 这是阶段二（接入完整对话并对接任务系统）的**唯一替换点**：真实对话接进来后，
/// 本常量与 `placeholder_view` 一起删除，客户端的 `dialog.source` 消费者同步下线。
pub const PLACEHOLDER_DIALOGUE: &str = "placeholder";

/// 占位提示的玩家可见文案：产品默认简体，`en` 供 `?lang=en`。
const PLACEHOLDER_TEXT_ZH: &str = "这个 NPC 的对话内容尚未实装。";
const PLACEHOLDER_TEXT_EN: &str = "This NPC's dialogue has not been implemented yet.";

/// 无脚本 NPC 的占位视图：一个 `ok` 节点（关闭即结束）外加来源标记。
///
/// 视图与标记必须一起产出——只给视图等于让客户端把占位当成本人台词，只给标记则
/// 玩家什么都看不到。
pub fn placeholder_view(
    request_id: &str,
    npc_id: &str,
    name: &str,
    name_zh: Option<&str>,
    lang: &str,
) -> serde_json::Value {
    let mut value = DialogueView::Say {
        text: if lang == crate::quest_text::LANG_EN {
            PLACEHOLDER_TEXT_EN
        } else {
            PLACEHOLDER_TEXT_ZH
        }
        .to_owned(),
        kind: "ok".to_owned(),
        options: Vec::new(),
    }
    .to_json(request_id, npc_id, name, name_zh);
    value
        .get_mut("dialog")
        .and_then(serde_json::Value::as_object_mut)
        .expect("a say view always carries a dialog object")
        .insert(
            "source".to_owned(),
            serde_json::Value::String(PLACEHOLDER_DIALOGUE.to_owned()),
        );
    value
}

/// Resolve branch/act nodes until a node that waits for input is reached.
/// `branch_depth` bounds the data-driven chain so a malformed config can never
/// spin here.  Quest acts surface a one-shot effect the world applies; they
/// resolve to `End` so the accept/complete hand-off ends the conversation.
fn resolve(
    script: &DialogueScript,
    mut node_id: String,
    context: &DialogueContext<'_>,
) -> Result<(String, DialogueView, Option<QuestEffect>), String> {
    let mut effect = None;
    for _ in 0..64 {
        let Some(node) = script.nodes.get(&node_id) else {
            return Err(format!("unknown npc dialogue node {node_id}"));
        };
        match node {
            DialogueNode::Branch(branch) => {
                node_id = if branch.cond.matches(context) {
                    branch.then.clone()
                } else {
                    branch.otherwise.clone()
                };
            }
            DialogueNode::Act(act) => {
                if act.kind == "jobAdvance" {
                    if effect.is_some() {
                        return Err("npc dialogue has multiple one-shot actions".to_owned());
                    }
                    let (Some(from_job), Some(job)) = (act.from_job, act.job) else {
                        return Err("npc dialogue jobAdvance requires fromJob and job".to_owned());
                    };
                    effect = Some(QuestEffect::JobAdvance { from_job, job });
                    if let Some(next) = act.next.clone() {
                        node_id = next;
                        continue;
                    }
                }
                return Ok((
                    node_id,
                    match act.kind.as_str() {
                        "shop" => match act.shop_id.clone() {
                            Some(shop_id) => DialogueView::OpenShop { shop_id },
                            None => DialogueView::End,
                        },
                        "warp" => match act.map_id.clone() {
                            Some(map_id) => DialogueView::Warp { map_id },
                            None => DialogueView::End,
                        },
                        "quest" => DialogueView::End,
                        _ => DialogueView::End,
                    },
                    effect.or_else(|| match (act.kind.as_str(), act.quest_id.as_deref()) {
                        ("quest", Some(quest_id)) => match act.quest_action.as_deref() {
                            Some("complete") => Some(QuestEffect::Complete(quest_id.to_owned())),
                            _ => Some(QuestEffect::Start(quest_id.to_owned())),
                        },
                        _ => None,
                    }),
                ));
            }
            DialogueNode::Say(say) => {
                return Ok((
                    node_id,
                    DialogueView::Say {
                        text: say.text.pick(context.lang).to_owned(),
                        kind: say.kind.clone(),
                        options: Vec::new(),
                    },
                    effect,
                ));
            }
            DialogueNode::Ask(ask) => {
                return Ok((
                    node_id,
                    DialogueView::Say {
                        text: ask.text.pick(context.lang).to_owned(),
                        kind: "yesNo".to_owned(),
                        options: Vec::new(),
                    },
                    effect,
                ));
            }
            DialogueNode::Menu(menu) => {
                return Ok((
                    node_id,
                    DialogueView::Say {
                        text: menu.text.pick(context.lang).to_owned(),
                        kind: "simple".to_owned(),
                        options: menu
                            .options
                            .iter()
                            .map(|option| (option.index, option.text.pick(context.lang).to_owned()))
                            .collect(),
                    },
                    effect,
                ));
            }
        }
    }
    Err("npc dialogue did not settle".to_owned())
}

/// Advance one step.  `current` is `None` when a conversation starts.
pub fn advance(
    script: &DialogueScript,
    current: Option<&str>,
    step: Option<&str>,
    selection: Option<u32>,
    context: &DialogueContext<'_>,
) -> Result<(String, DialogueView, Option<QuestEffect>), String> {
    let Some(current) = current else {
        if step.is_some_and(|step| step != "start") {
            return Err("npc conversation has not started".to_owned());
        }
        return resolve(script, script.start.clone(), context);
    };
    if step == Some("start") {
        return resolve(script, script.start.clone(), context);
    }
    if step == Some("end") {
        return Ok((current.to_owned(), DialogueView::End, None));
    }
    let Some(node) = script.nodes.get(current) else {
        return Err(format!("unknown npc dialogue node {current}"));
    };
    let next_id = match (node, step, selection) {
        (DialogueNode::Say(say), Some("next"), _) => {
            let Some(next) = say.next.clone() else {
                return Ok((current.to_owned(), DialogueView::End, None));
            };
            next
        }
        (DialogueNode::Say(say), Some("prev"), _) => {
            let Some(prev) = say.prev.clone() else {
                return Ok((current.to_owned(), DialogueView::End, None));
            };
            prev
        }
        // `sendOk` copies close on any confirmation.
        (DialogueNode::Say(say), _, _) if say.kind == "ok" => {
            return Ok((current.to_owned(), DialogueView::End, None))
        }
        (DialogueNode::Ask(ask), Some("yes"), _) => ask.yes.clone(),
        (DialogueNode::Ask(ask), Some("no"), _) => ask.no.clone(),
        (DialogueNode::Menu(menu), Some("select"), Some(selection)) => {
            let Some(option) = menu.options.iter().find(|option| option.index == selection) else {
                return Err("npc dialogue selection is not offered".to_owned());
            };
            option.next.clone()
        }
        _ => return Err("npc dialogue step is not offered".to_owned()),
    };
    resolve(script, next_id, context)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn script() -> DialogueScript {
        serde_json::from_str(
            r#"{"start":"a","nodes":{
                "a":{"say":{"text":"first","kind":"next","next":"b"}},
                "b":{"ask":{"text":"really?","yes":"shop","no":"bye"}},
                "shop":{"act":{"kind":"shop","shopId":"11000"}},
                "bye":{"say":{"text":"ok","kind":"ok"}},
                "gate":{"branch":{"cond":{"levelAtLeast":7},"then":"a","else":"bye"}},
                "qgate":{"branch":{"cond":{"questAvailable":"q1"},"then":"offer","else":"bye"}},
                "offer":{"act":{"kind":"quest","questId":"q1","questAction":"start"}},
                "finish":{"act":{"kind":"quest","questId":"q1","questAction":"complete"}},
                "menu":{"menu":{"text":"pick","options":[{"index":0,"text":"one","next":"a"}]}}}}"#,
        )
        .unwrap()
    }

    fn context(level: u32, mesos: u64) -> DialogueContext<'static> {
        fn empty_quests() -> &'static BTreeMap<String, String> {
            Box::leak(Box::new(BTreeMap::new()))
        }
        DialogueContext {
            hp: 50,
            level,
            mesos,
            inventory: &[],
            quests: empty_quests(),
            lang: "zh",
        }
    }

    fn quest_context<'a>(quests: &'a BTreeMap<String, String>) -> DialogueContext<'a> {
        DialogueContext {
            hp: 50,
            level: 1,
            mesos: 0,
            inventory: &[],
            quests,
            lang: "zh",
        }
    }

    #[test]
    fn start_resolves_to_the_first_waiting_node() {
        let script = script();
        let (node, view, effect) = advance(&script, None, None, None, &context(1, 0)).unwrap();
        assert_eq!(node, "a");
        assert_eq!(effect, None);
        assert_eq!(
            view,
            DialogueView::Say {
                text: "first".into(),
                kind: "next".into(),
                options: vec![]
            }
        );
    }

    #[test]
    fn yes_no_branches_resolve_terminal_actions() {
        let script = script();
        let (_, view, _) = advance(&script, Some("a"), Some("next"), None, &context(1, 0)).unwrap();
        assert_eq!(
            view,
            DialogueView::Say {
                text: "really?".into(),
                kind: "yesNo".into(),
                options: vec![]
            }
        );
        let (_, view, _) = advance(&script, Some("b"), Some("yes"), None, &context(1, 0)).unwrap();
        assert_eq!(
            view,
            DialogueView::OpenShop {
                shop_id: "11000".into()
            }
        );
        let (_, view, _) = advance(&script, Some("b"), Some("no"), None, &context(1, 0)).unwrap();
        assert_eq!(
            view,
            DialogueView::Say {
                text: "ok".into(),
                kind: "ok".into(),
                options: vec![]
            }
        );
    }

    #[test]
    fn branch_conditions_gate_the_target() {
        let script: DialogueScript = serde_json::from_str(
            r#"{"start":"gate","nodes":{
                "gate":{"branch":{"cond":{"levelAtLeast":7},"then":"a","else":"bye"}},
                "a":{"say":{"text":"big","kind":"ok"}},
                "bye":{"say":{"text":"small","kind":"ok"}}}}"#,
        )
        .unwrap();
        let (node, _, _) = advance(&script, None, None, None, &context(9, 0)).unwrap();
        assert_eq!(node, "a");
        let (node, _, _) = advance(&script, None, None, None, &context(2, 0)).unwrap();
        assert_eq!(node, "bye");
    }

    #[test]
    fn quest_conditions_gate_offers_and_effects_surface() {
        let offer: DialogueScript = serde_json::from_str(
            r#"{"start":"qgate","nodes":{
                "qgate":{"branch":{"cond":{"questAvailable":"q1"},"then":"offer","else":"bye"}},
                "offer":{"act":{"kind":"quest","questId":"q1","questAction":"start"}},
                "bye":{"say":{"text":"ok","kind":"ok"}}}}"#,
        )
        .unwrap();
        let empty = BTreeMap::new();
        // Available: the offer branch lands on the quest act and surfaces a
        // Start effect; the conversation ends.
        let (_, view, effect) = advance(&offer, None, None, None, &quest_context(&empty)).unwrap();
        assert_eq!(view, DialogueView::End);
        assert_eq!(effect, Some(QuestEffect::Start("q1".to_owned())));
        // Active: no longer available, so the offer branch is skipped.
        let active = BTreeMap::from([("q1".to_owned(), "active".to_owned())]);
        let (node, _, effect) = advance(&offer, None, None, None, &quest_context(&active)).unwrap();
        assert_eq!(node, "bye");
        assert_eq!(effect, None);

        let finish: DialogueScript = serde_json::from_str(
            r#"{"start":"finish","nodes":{
                "finish":{"act":{"kind":"quest","questId":"q1","questAction":"complete"}}}}"#,
        )
        .unwrap();
        let (_, view, effect) =
            advance(&finish, None, None, None, &quest_context(&active)).unwrap();
        assert_eq!(view, DialogueView::End);
        assert_eq!(effect, Some(QuestEffect::Complete("q1".to_owned())));
    }

    #[test]
    fn menu_requires_an_offered_selection() {
        let script: DialogueScript = serde_json::from_str(
            r#"{"start":"menu","nodes":{
                "menu":{"menu":{"text":"pick","options":[{"index":0,"text":"one","next":"a"}]}},
                "a":{"say":{"text":"chosen","kind":"ok"}}}}"#,
        )
        .unwrap();
        let (_, view, _) = advance(&script, None, None, None, &context(1, 0)).unwrap();
        assert!(matches!(view, DialogueView::Say { kind, .. } if kind == "simple"));
        assert!(advance(
            &script,
            Some("menu"),
            Some("select"),
            Some(4),
            &context(1, 0)
        )
        .is_err());
        let (node, _, _) = advance(
            &script,
            Some("menu"),
            Some("select"),
            Some(0),
            &context(1, 0),
        )
        .unwrap();
        assert_eq!(node, "a");
    }

    #[test]
    fn job_advance_keeps_the_success_say_after_applying_effect() {
        let script: DialogueScript = serde_json::from_str(
            r#"{"start":"menu","nodes":{
                "menu":{"menu":{"text":"choose","options":[{"index":0,"text":"Magician","next":"advance"}]}},
                "advance":{"act":{"kind":"jobAdvance","fromJob":0,"job":200,"next":"success"}},
                "success":{"say":{"text":"advanced","kind":"ok"}}}}"#,
        )
        .unwrap();
        let context = context(1, 0);
        let (node, view, _effect) = advance(&script, None, Some("start"), None, &context).unwrap();
        assert_eq!(node, "menu");
        assert!(matches!(view, DialogueView::Say { kind, .. } if kind == "simple"));
        let (node, view, effect) =
            advance(&script, Some("menu"), Some("select"), Some(0), &context).unwrap();
        assert_eq!(node, "success");
        assert_eq!(
            view,
            DialogueView::Say {
                text: "advanced".into(),
                kind: "ok".into(),
                options: vec![]
            }
        );
        assert_eq!(
            effect,
            Some(QuestEffect::JobAdvance {
                from_job: 0,
                job: 200
            })
        );

        let malformed: DialogueScript = serde_json::from_str(
            r#"{"start":"advance","nodes":{"advance":{"act":{"kind":"jobAdvance","job":200}}}}"#,
        )
        .unwrap();
        assert!(advance(&malformed, None, Some("start"), None, &context).is_err());
    }

    #[test]
    fn localized_text_picks_locale_then_english() {
        let map: LocalizedText = serde_json::from_str(r#"{"en":"Hello","zh":"你好"}"#).unwrap();
        assert_eq!(map.pick("zh"), "你好");
        assert_eq!(map.pick("en"), "Hello");
        // Unknown locale falls back to English.
        assert_eq!(map.pick("fr"), "Hello");
        let plain: LocalizedText = serde_json::from_str(r#""legacy""#).unwrap();
        assert_eq!(plain.pick("zh"), "legacy");
        assert_eq!(plain.pick("en"), "legacy");
    }

    #[test]
    fn bilingual_say_resolves_in_the_player_language() {
        let script: DialogueScript = serde_json::from_str(
            r#"{"start":"a","nodes":{
                "a":{"say":{"text":{"en":"Hello","zh":"你好"},"kind":"ok"}}}}"#,
        )
        .unwrap();
        let zh = context(1, 0);
        let (_, view, _) = advance(&script, None, None, None, &zh).unwrap();
        assert_eq!(
            view,
            DialogueView::Say {
                text: "你好".into(),
                kind: "ok".into(),
                options: vec![]
            }
        );
        let mut en = context(1, 0);
        en.lang = "en";
        let (_, view, _) = advance(&script, None, None, None, &en).unwrap();
        assert_eq!(
            view,
            DialogueView::Say {
                text: "Hello".into(),
                kind: "ok".into(),
                options: vec![]
            }
        );
    }

    #[test]
    fn bilingual_menu_localizes_lead_and_options() {
        let script: DialogueScript = serde_json::from_str(
            r#"{"start":"m","nodes":{
                "m":{"menu":{
                    "text":{"en":"Ask away!","zh":"尽管问吧！"},
                    "options":[
                        {"index":0,"text":{"en":"How do I move?","zh":"怎么移动？"},"next":"a"}
                    ]}},
                "a":{"say":{"text":"bye","kind":"ok"}}}}"#,
        )
        .unwrap();
        let (_, view, _) = advance(&script, None, None, None, &context(1, 0)).unwrap();
        match view {
            DialogueView::Say {
                text,
                kind,
                options,
            } => {
                assert_eq!(kind, "simple");
                assert_eq!(text, "尽管问吧！");
                assert_eq!(options, vec![(0, "怎么移动？".to_owned())]);
            }
            other => panic!("expected say view, got {other:?}"),
        }
    }

    #[test]
    fn steps_that_the_node_does_not_offer_are_rejected() {
        let script = script();
        // A `next` step on the ask node (which only offers yes/no) is invalid.
        assert!(advance(&script, Some("b"), Some("next"), None, &context(1, 0)).is_err());
        // A `prev` step on a page with no prev edge falls back to closing.
        let (_, view, _) = advance(&script, Some("a"), Some("prev"), None, &context(1, 0)).unwrap();
        assert_eq!(view, DialogueView::End);
    }
}
