// Offline real-3D check: isolated inline renderer, no file navigation or game service.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader'],...(process.env.PLAYWRIGHT_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE}:{})});
 const out=path.resolve('artifacts/henesys/east-village');fs.mkdirSync(out,{recursive:true});const errors=[],network=[],html=fs.readFileSync('docs/design/prototypes/chuxian-east-village.html','utf8');
 try{
  const page=await browser.newPage({viewport:{width:1560,height:980},acceptDownloads:true});page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});
  await page.setContent(html);await page.waitForFunction(()=>window.chuxianEast3D?.ready,null,{timeout:60000});await page.locator('#roam').uncheck();
  assert.equal(await page.evaluate(()=>chuxianEast3D.mode),'game');
  const fixedPose=await page.evaluate(()=>({eye:chuxianEast3D.camera.position.toArray(),target:chuxianEast3D.controls.target.toArray()}));
  await page.mouse.move(950,650);await page.mouse.down();await page.mouse.move(1060,690,{steps:6});await page.mouse.up();
  assert.deepEqual(await page.evaluate(()=>({eye:chuxianEast3D.camera.position.toArray(),target:chuxianEast3D.controls.target.toArray()})),fixedPose,'game camera angle must remain locked');
  await page.locator('#collapse-tools').click();await page.screenshot({path:path.join(out,'3d-height-game.png')});
  const fixedView=await page.evaluate(()=>{
    const p=chuxianEast3D,V=p.camera.position.constructor;
    function test(source,target,t=1){p.selected.p.copy(p.nodeMap[source]);p.selected.path=[];p.view('game');p.camera.updateMatrixWorld();const q=p.nodeMap[source].clone().lerp(p.nodeMap[target],t).add(new V(0,.2,0)),d=q.distanceTo(p.camera.position);p.ray.set(p.camera.position,q.clone().sub(p.camera.position).normalize());p.ray.far=d-.05;const hits=p.ray.intersectObjects(p.layers.terrain,true);p.ray.far=Infinity;return {source,target,hiddenByTerrain:!!hits.length,firstBlocker:hits[0]?.object.name,pitch:Math.asin(p.camera.position.clone().sub(p.controls.target).normalize().y),screen:p.project(q)};}
    const heights=Object.values(p.nodeMap).map(v=>v.y),main=p.layout.routes.find(r=>r.name==='晨光大道').points.map(id=>p.nodeMap[id].y);
    return {fov:p.camera.fov,mainRise:Math.max(...main)-Math.min(...main),riverDrop:p.nodeMap.central.y-p.nodeMap.dockHead.y,guildRise:p.nodeMap.hallFrontW.y-p.nodeMap.central.y,totalRise:Math.max(...heights)-Math.min(...heights),flowerEntry:test('central','gardenW'),flowerHidden:test('central','gardenN'),rootEntry:test('groveMid','rootHollow',.12),rootHidden:test('groveCross','rootHollow')};
  });console.log('FIXED TERRAIN',JSON.stringify(fixedView));
  assert.equal(fixedView.fov,38);assert(fixedView.mainRise>=6);assert(fixedView.riverDrop>=6);assert(fixedView.guildRise>=15);
  for(const result of [fixedView.flowerEntry,fixedView.rootEntry])assert(!result.hiddenByTerrain,'branch entrance must show: '+JSON.stringify(result));
  for(const result of [fixedView.flowerHidden,fixedView.rootHidden]){assert(result.hiddenByTerrain,'hidden lane must be covered by real terrain: '+JSON.stringify(result));assert(Math.abs(result.pitch-.24)<1e-8);}
  for(const [entry,inside,name] of [['gardenW','gardenN','flower'],['groveCross','rootHollow','root']]){
    await page.evaluate(id=>{const p=chuxianEast3D;p.selected.p.copy(p.nodeMap[id]);p.selected.path=[];p.view('game');},entry);
    await page.screenshot({path:path.join(out,'3d-height-'+name+'-entrance.png')});
    assert(await page.evaluate(id=>chuxianEast3D.go(chuxianEast3D.selected,chuxianEast3D.nodeMap[id]),inside),'hidden place must be reachable');
    await page.evaluate(id=>{const p=chuxianEast3D;p.selected.p.copy(p.nodeMap[id]);p.selected.path=[];p.view('game');},inside);
    await page.screenshot({path:path.join(out,'3d-height-'+name+'-inside.png')});
    const visible=await page.evaluate(()=>{const p=chuxianEast3D,V=p.camera.position.constructor,q=p.selected.p.clone().add(new V(0,.16,0)),d=q.distanceTo(p.camera.position);p.ray.set(p.camera.position,q.clone().sub(p.camera.position).normalize());p.ray.far=d-.05;const hits=p.ray.intersectObjects([...p.layers.terrain,...p.layers.roads],true);p.ray.far=Infinity;return !hits.length;});assert(visible,'player must reappear inside hidden lane '+name);
  }
  await page.evaluate(()=>{const p=chuxianEast3D;p.selected.p.copy(p.nodeMap.central);p.selected.path=[];p.view('game');p.go(p.selected,p.nodeMap.gardenFront);});
  const fixedStart=await page.evaluate(()=>({foot:chuxianEast3D.selected.p.x,eye:chuxianEast3D.camera.position.x}));
  await page.waitForFunction(q=>chuxianEast3D.selected.p.x-q.foot>.2&&chuxianEast3D.camera.position.x-q.eye>.05,fixedStart);
  assert(Math.abs(await page.evaluate(()=>Math.asin(chuxianEast3D.camera.position.clone().sub(chuxianEast3D.controls.target).normalize().y))-.24)<1e-8,'following must keep game pitch');
  await page.evaluate(()=>{chuxianEast3D.reset();chuxianEast3D.view('east');});await page.locator('#collapse-tools').click();await page.locator('#roam').uncheck();
  const surfaceIntrusions=await page.evaluate(()=>{const p=chuxianEast3D,V=p.camera.position.constructor,issues=[];for(const s of p.segments)for(const t of [.25,.5,.75]){const q=s.a.clone().lerp(s.b,t);p.ray.set(q.clone().add(new V(0,30,0)),new V(0,-1,0));p.ray.far=Infinity;const hit=p.ray.intersectObjects(p.layers.terrain,true)[0];if(hit&&hit.point.y-q.y>.1)issues.push({route:s.route.name,id:s.id,t,rise:hit.point.y-q.y,mesh:hit.object.name,point:q.toArray()});}return issues.sort((a,b)=>b.rise-a.rise);});console.log('TERRAIN INTRUSIONS',JSON.stringify(surfaceIntrusions.slice(0,12)));assert.equal(surfaceIntrusions.length,0,'soil must stay below walking centre lines');
  const geometry=await page.evaluate(()=>{
   const p=chuxianEast3D,V=p.camera.position.constructor;let footError=0,legError=0;for(const [id,node] of Object.entries(p.nodeMap)){
    const start=p.nearest(p.nodeMap.central),end=p.nearest(node),route=p.pathBetween(start,end);if(!route.length)throw Error('Unreachable '+id);let prev=start.p;for(const q of route){legError=Math.max(legError,p.nearest(prev.clone().lerp(q,.5)).distance);prev=q;}
    p.ray.set(node.clone().add(new V(0,25,0)),new V(0,-1,0));const hits=p.ray.intersectObjects(p.roads,true);if(!hits.length)throw Error('No solid road at '+id);footError=Math.max(footError,Math.min(...hits.map(h=>Math.abs(h.point.y-node.y))));}
   return {webgl2:document.querySelector('#scene').getContext('webgl2') instanceof WebGL2RenderingContext,perspective:p.camera.isPerspectiveCamera,sourceObjects:p.model.children.length,layers:Object.fromEntries(Object.entries(p.layers).map(([k,v])=>[k,v.length])),nodes:Object.keys(p.nodeMap).length,routes:p.layout.routes.length,players:p.roles.filter(r=>r.type==='player').length,npcs:p.roles.filter(r=>r.type==='npc').length,footError,legError};
  });assert(geometry.webgl2&&geometry.perspective);assert(geometry.sourceObjects>300);assert.equal(geometry.layers.buildings,11);assert.equal(geometry.routes,16);assert.equal(geometry.players,32);assert.equal(geometry.npcs,7);assert(geometry.footError<.05);assert(geometry.legError<1e-7);
  const bounds=await page.locator('#scene').boundingBox();const point=await page.evaluate(()=>{const p=chuxianEast3D;return p.project(p.nodeMap.central.clone().lerp(p.nodeMap.gardenFront,.28));});
  await page.mouse.click(bounds.x+point.x,bounds.y+point.y);assert(await page.evaluate(()=>chuxianEast3D.selected.id==='self'&&chuxianEast3D.selected.path.length>0),'ground click must walk selected player');
  const before=await page.evaluate(()=>chuxianEast3D.selected.p.x);await page.waitForFunction(x=>Math.abs(chuxianEast3D.selected.p.x-x)>.15,before,{timeout:10000});await page.locator('#stop').click();
  const start=await page.evaluate(()=>{const p=chuxianEast3D,V=p.camera.position.constructor;return p.project(p.selected.p.clone().add(new V(0,.8,0)));});
  const target=await page.evaluate(()=>{const p=chuxianEast3D;return p.project(p.nodeMap.central.clone().lerp(p.nodeMap.gardenFront,.65));});
  await page.mouse.move(bounds.x+start.x,bounds.y+start.y);await page.mouse.down();await page.mouse.move(bounds.x+target.x,bounds.y+target.y,{steps:8});await page.mouse.up();assert.equal(await page.evaluate(()=>chuxianEast3D.selected.id),'self');assert((await page.evaluate(()=>chuxianEast3D.nearest(chuxianEast3D.selected.p).distance))<1e-6);assert((await page.evaluate(()=>{const p=chuxianEast3D;return p.selected.p.distanceTo(p.nodeMap.central.clone().lerp(p.nodeMap.gardenFront,.65));}))<1,'actual drag must reach the requested road point');
  await page.locator('[data-place="guild"]').click();assert.equal(await page.locator('#zoom').getAttribute('max'),'420');const gate=await page.evaluate(()=>chuxianEast3D.project(chuxianEast3D.nodeMap.hallFrontE));
  await page.locator('#add-player').click();await page.mouse.click(bounds.x+gate.x,bounds.y+gate.y);if((await page.evaluate(()=>chuxianEast3D.roles.filter(r=>r.type==='player').length))!==33){console.log('PLACEMENT DEBUG',await page.evaluate(q=>({placing:chuxianEast3D.placing,toast:document.querySelector('#toast').textContent,element:document.elementFromPoint(q.x,q.y)?.outerHTML.slice(0,250),camera:chuxianEast3D.camera.position.toArray()}),{x:bounds.x+gate.x,y:bounds.y+gate.y}));await page.screenshot({path:path.join(out,'3d-interaction-failure.png')});}assert.equal(await page.evaluate(()=>chuxianEast3D.roles.filter(r=>r.type==='player').length),33);
  await page.locator('#add-npc').click();await page.mouse.click(bounds.x+gate.x+20,bounds.y+gate.y);assert.equal(await page.evaluate(()=>chuxianEast3D.roles.filter(r=>r.type==='npc').length),8);assert(await page.locator('#dialogue').isVisible());await page.locator('#close-dialogue').click();
  await page.locator('#delete-role').click();assert.equal(await page.evaluate(()=>chuxianEast3D.roles.filter(r=>r.type==='npc').length),7);
  const pose=await page.evaluate(()=>chuxianEast3D.camera.position.toArray());await page.mouse.move(900,420);await page.mouse.down();await page.mouse.move(1030,440,{steps:7});await page.mouse.up();assert.notDeepEqual(await page.evaluate(()=>chuxianEast3D.camera.position.toArray()),pose,'drag must rotate real camera');
  const d=await page.evaluate(()=>chuxianEast3D.camera.position.distanceTo(chuxianEast3D.controls.target));await page.mouse.wheel(0,-120);await page.waitForFunction(x=>chuxianEast3D.camera.position.distanceTo(chuxianEast3D.controls.target)<x,d);
  await page.locator('[data-view="game"]').click();assert(Math.abs(await page.evaluate(()=>Math.asin(chuxianEast3D.camera.position.clone().sub(chuxianEast3D.controls.target).normalize().y))-.24)<1e-8);
  await page.locator('[data-view="east"]').click();
  const original=await page.evaluate(()=>Object.fromEntries(Object.entries(chuxianEast3D.layers).map(([k,v])=>[k,v.map(o=>o.position.toArray())])));await page.locator('#explode').click();assert(await page.evaluate(()=>chuxianEast3D.exploded&&!chuxianEast3D.people.visible));await page.locator('[data-view="overview"]').click();await page.screenshot({path:path.join(out,'3d-final-layers.png')});await page.locator('#explode').click();assert.deepEqual(await page.evaluate(()=>Object.fromEntries(Object.entries(chuxianEast3D.layers).map(([k,v])=>[k,v.map(o=>o.position.toArray())]))),original);
  for(const n of [12,64,32]){await page.locator('#density').selectOption(String(n));assert.equal(await page.evaluate(()=>chuxianEast3D.roles.filter(r=>r.type==='player').length),n);}
  await page.locator('#roam').check();await page.waitForFunction(()=>chuxianEast3D.roles.some(r=>r.type==='player'&&r.id!==chuxianEast3D.selected.id&&r.path.length));await page.locator('#roam').uncheck();assert(await page.evaluate(()=>chuxianEast3D.roles.filter(r=>r.type==='player'&&r.id!==chuxianEast3D.selected.id).every(r=>!r.path.length)));
  await page.locator('#routes').check();await page.locator('#labels').check();await page.locator('#rays').uncheck();await page.locator('#rays').check();await page.locator('#sunlight').fill('2.5');
  await page.locator('#reset-layout').click();await page.locator('#roam').uncheck();await page.locator('[data-view="east"]').click();await page.locator('#collapse-tools').click();await page.screenshot({path:path.join(out,'3d-final-east.png')});
  for(const [id,file] of [['guild','guild'],['garden','garden'],['riverside','river']]){await page.locator(`[data-place="${id}"]`).click();await page.screenshot({path:path.join(out,'3d-final-'+file+'.png')});}
  await page.locator('[data-view="stroll"]').click();assert.equal(await page.evaluate(()=>chuxianEast3D.mode),'stroll');await page.screenshot({path:path.join(out,'3d-final-stroll.png')});
  const download=page.waitForEvent('download');await page.locator('#save-image').click();assert((await download).suggestedFilename().endsWith('.png'));
  await page.setViewportSize({width:390,height:844});await page.locator('[data-view="east"]').click();const mobile=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,buttonsFit:[...document.querySelectorAll('header button')].every(b=>b.getBoundingClientRect().right<=innerWidth),statsClear:document.querySelector('.stats').getBoundingClientRect().bottom<document.querySelector('.view-controls').getBoundingClientRect().top}));assert(mobile.scroll<=mobile.width);assert(mobile.buttonsFit);assert(mobile.statsClear);await page.screenshot({path:path.join(out,'3d-final-mobile.png')});
  assert.deepEqual(errors,[]);assert.deepEqual(network,[]);fs.writeFileSync(path.join(out,'3d-check.json'),JSON.stringify({geometry,fixedView,surfaceIntrusions,mobile,checks:['graded roads and low fixed camera','visible branch entries, terrain-hidden lanes, revealed on approach','solid walkable curves and connected 3D navigation','real perspective rotation and zoom','depth-tested 2D sprite placement/drag/walk','NPC dialogue','explode and exact restore','12/32/64 players and pause','landmarks and stroll','PNG export and mobile','zero external assets'],errors,network,renderer:'isolated Chromium SwiftShader; no native GPU performance claim'},null,2)+'\n','utf8');console.log('PASS real 3D east village:',JSON.stringify({geometry,fixedView,mobile}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
