const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const { createRequire } = require('node:module');
const root = path.resolve(__dirname, '..'), output = path.join(root, 'build/.checks/voyage-login.cjs');
fs.mkdirSync(path.dirname(output), { recursive: true });
createRequire(path.join(root, 'client/package.json'))('esbuild').buildSync({ stdin: { contents: "export * from './voyage-login'; export * as Three from 'three';", resolveDir: path.join(root, 'client/src/features/entry'), loader: 'ts' }, bundle: true, platform: 'node', format: 'cjs', outfile: output, logLevel: 'silent' });
const { Three: T, projectLoginSurface, loginSurfaceOccluded, VoyageLogin } = require(output);
const viewport = { width: 1440, height: 900 }, pixels = { width: 430, height: 360 };
const camera = new T.PerspectiveCamera(46, viewport.width / viewport.height, 1, 1000);
camera.position.set(1, 2, 14); camera.lookAt(0, 1, 0);
const ship = new T.Group(), anchor = new T.Object3D(); ship.add(anchor);
const surface = { anchor, width: 5, height: 4 };
anchor.position.set(-1, 1, 0); ship.rotation.set(.05, .4, -.08); ship.scale.set(1.2, .8, 1.1);
const close = (actual, expected) => assert(Math.abs(actual - expected) < 1e-7, `${actual} != ${expected}`);
const at = (matrix, x, y) => new T.Vector3(x, y, 0).applyMatrix4(matrix);
const projection = projectLoginSurface(surface, camera, viewport, pixels);
assert(projection, 'authored surface must project from its front');
// Independent world-space corners prove the CSS matrix includes ship rotation/scale and camera perspective.
const scale = Math.min(5 / 430, 4 / 360);
for (const [x, y] of [[0, 0], [430, 0], [430, 360], [0, 360], [100, 90]]) {
  const world = new T.Vector3((x - 215) * scale, (180 - y) * scale, 0).applyMatrix4(anchor.matrixWorld).project(camera);
  const css = at(projection.matrix, x, y);
  close(css.x, (world.x + 1) * 720); close(css.y, (1 - world.y) * 450);
}
assert(Math.abs(projection.matrix.elements[3]) > 1e-5, 'an angled sign must have perspective division, not screen translation');
const leftHeight = at(projection.matrix, 0, 0).distanceTo(at(projection.matrix, 0, 360));
const rightHeight = at(projection.matrix, 430, 0).distanceTo(at(projection.matrix, 430, 360));
assert(Math.abs(leftHeight - rightHeight) > 1, 'the far edge must foreshorten');
ship.position.x += 2;
const moved = projectLoginSurface(surface, camera, viewport, pixels);
assert(moved && Math.abs(at(moved.matrix, 215, 180).x - at(projection.matrix, 215, 180).x) > 10, 'a moving ship moves the form');
const resized = projectLoginSurface(surface, camera, { width: 720, height: 450 }, pixels);
close(at(resized.matrix, 215, 180).x, at(moved.matrix, 215, 180).x / 2);
ship.visible = false; assert.equal(projectLoginSurface(surface, camera, viewport, pixels), undefined); ship.visible = true;
for (const width of [0, -1, NaN, Infinity]) assert.equal(projectLoginSurface({ ...surface, width }, camera, viewport, pixels), undefined);
assert.equal(projectLoginSurface(surface, camera, viewport, { ...pixels, height: 0 }), undefined);
ship.scale.x = 0; assert.equal(projectLoginSurface(surface, camera, viewport, pixels), undefined); ship.scale.set(1, 1, 1);
ship.rotation.set(0, 0, 0); ship.position.set(0, 0, 0); anchor.position.set(0, 0, -10);
camera.position.set(0, 0, 0); camera.lookAt(0, 0, -1);
const front = projectLoginSurface(surface, camera, viewport, pixels); assert(front);
anchor.rotation.y = Math.PI; assert.equal(projectLoginSurface(surface, camera, viewport, pixels), undefined); anchor.rotation.y = 0;
anchor.position.z = -.5; assert.equal(projectLoginSurface(surface, camera, viewport, pixels), undefined, 'near-plane crossing is hidden');
anchor.position.z = -1002; assert.equal(projectLoginSurface(surface, camera, viewport, pixels), undefined, 'far-plane clipping is hidden');
anchor.position.set(1000, 0, -10); assert.equal(projectLoginSurface(surface, camera, viewport, pixels), undefined, 'offscreen forms cannot intercept input');
anchor.position.set(5, 0, -10); assert(projectLoginSurface(surface, camera, viewport, pixels), 'partially visible plane stays perspective-correct');
anchor.position.set(NaN, 0, -10); assert.equal(projectLoginSurface(surface, camera, viewport, pixels), undefined);
anchor.position.set(0, 0, -10);
const blocker = new T.Mesh(new T.BoxGeometry(6, 6, .2), new T.MeshBasicMaterial()), cover = new T.Group(); cover.add(blocker);
blocker.position.z = -5;
assert(loginSurfaceOccluded(camera, front.points, [cover]), 'opaque geometry in front hides the form');
cover.visible = false; assert(!loginSurfaceOccluded(camera, front.points, [cover]), 'hidden ancestors cannot occlude'); cover.visible = true;
blocker.position.z = -12; assert(!loginSurfaceOccluded(camera, front.points, [cover]), 'backing behind the surface cannot occlude');
blocker.position.z = -.5; assert(!loginSurfaceOccluded(camera, front.points, [cover]), 'geometry clipped before camera near cannot occlude');
blocker.position.z = -5; blocker.material.transparent = true; assert(!loginSurfaceOccluded(camera, front.points, [cover]), 'glass is not an opaque blocker'); blocker.material.transparent = false;
blocker.layers.set(2); assert(!loginSurfaceOccluded(camera, front.points, [cover]), 'camera layer masks match WebGL'); blocker.layers.set(0);
blocker.position.set(1.18, .98, -5); blocker.scale.set(.1, .1, 1);
assert(loginSurfaceOccluded(camera, front.points, [cover]), 'corner obstruction cannot leave a clickable form on top of geometry');

// Minimal DOM stand-in checks lifecycle and input ownership; browser interaction is an integration check.
const makeForm = () => ({ style: { cssText: 'color:red' }, inert: false, offsetWidth: 430, offsetHeight: 360, listeners: new Map(), addEventListener(type, fn) { this.listeners.set(type, fn); }, removeEventListener(type, fn) { if (this.listeners.get(type) === fn) this.listeners.delete(type); } });
let form = makeForm(), reveals = 0;
const submit = () => {}; form.addEventListener('submit', submit);
const host = { clientWidth: 1440, clientHeight: 900, querySelector: () => form };
const login = new VoyageLogin(host, () => reveals++);
assert(login.update(camera, surface)); assert.equal(form.listeners.get('submit'), submit);
assert.match(form.style.transform, /^matrix3d\(/); assert.equal(form.inert, false);
form.listeners.get('keydown')(); assert.equal(reveals, 1);
anchor.rotation.y = Math.PI; assert.equal(login.update(camera, surface), false); assert.equal(form.inert, true); assert.equal(form.style.pointerEvents, 'none'); anchor.rotation.y = 0;
assert(login.update(camera, surface)); assert.equal(form.inert, false, 'returning to the front restores native input');
const previous = form; form = makeForm(); assert(login.update(camera, surface));
assert.equal(previous.style.cssText, 'color:red'); assert(!previous.listeners.has('keydown')); assert.equal(previous.listeners.get('submit'), submit);
login.update(camera); assert.equal(form.style.cssText, 'color:red'); assert.equal(form.inert, false); assert.equal(form.listeners.size, 0);
blocker.geometry.dispose(); blocker.material.dispose();
console.log('Voyage login perspective/ship motion/visibility/clipping/occlusion/DOM lifecycle checks passed');
