const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path');
const { createRequire } = require('node:module');
const root = path.resolve(__dirname, '..'), output = path.join(root, 'build/.checks/entry-music.cjs');
fs.mkdirSync(path.dirname(output), { recursive: true });
createRequire(path.join(root, 'client/package.json'))('esbuild').buildSync({ entryPoints: [path.join(root, 'client/src/features/entry/music.ts')], bundle: true, platform: 'node', format: 'cjs', outfile: output, logLevel: 'silent' });
const { EntryMusic } = require(output);
global.document = { hidden: false };
global.fetch = async () => ({ ok: true, arrayBuffer: async () => new ArrayBuffer(8) });
let context, starts = 0, stops = 0, releaseDecode;
const makeContext = () => ({ state: 'running', destination: {}, decodeAudioData: async () => ({}), createBufferSource: () => ({ connect() {}, disconnect() {}, start() { starts++; }, stop() { stops++; } }), createGain: () => ({ gain: { value: 0 }, connect() {}, disconnect() {} }) });
const tick = () => new Promise(resolve => setImmediate(resolve));
(async () => {
  const music = new EntryMusic(() => context);
  music.setTrack('/orbis.mp3'); music.setActive(true); await tick();
  assert.equal(starts, 0, 'loading music cannot manufacture an unlocked context');
  context = makeContext(); await music.resume(); assert(music.playing); assert.equal(starts, 1);
  await music.resume(); assert.equal(starts, 1, 'later gestures cannot stack looping sources');
  music.setMuted(true); assert.equal(music.playing, false); assert.equal(music.gain.gain.value, 0);
  music.setMuted(false); assert(music.playing); assert.equal(starts, 1);
  music.setActive(false); assert.equal(stops, 1); assert.equal(music.playing, false);
  document.hidden = true; music.setActive(true); await tick(); assert.equal(starts, 1);
  document.hidden = false; await music.resume(); assert.equal(starts, 2);
  music.dispose(); assert.equal(stops, 2);
  const late = new EntryMusic(() => context);
  context.decodeAudioData = () => new Promise(resolve => { releaseDecode = resolve; });
  late.setTrack('/orbis.mp3'); late.setActive(true); await tick(); late.setActive(false);
  releaseDecode({}); await tick(); assert.equal(starts, 2, 'async decode cannot start lobby audio after entry');
  late.dispose(); console.log('Entry music: shared unlock, one source, mute, visibility, stop and late decode passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
