#!/usr/bin/env python3
"""从高清素材生成 3010 启动脚本的终端字符画（zsh 源文件）。

默认源图：枫叶岛红枫树 client/public-tms273/assets/tms273/Map_Obj__Canvas_acc1.img_mapleIsland_maple_0_0-*.png
输出：scripts/launcher-art.zsh —— 提供 LAUNCHER_ART 数组与进度函数：
  launcher_art_init            重置已打印行数
  launcher_art_step DONE TOTAL 按 (DONE/TOTAL) 比例打印字符画到对应行
  launcher_art_finish          打印剩余全部行（完整字符画）

用法：gen_launcher_ascii_art.py [源图路径] [输出zsh路径] [宽度列数]
源图缺失时以非 0 退出，启动脚本会自动降级为纯文本进度。
"""
import glob
import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSET_DIR = os.path.join(ROOT, "client", "public-tms273", "assets", "tms273")
DEFAULT_PATTERN = "Map_Obj__Canvas_acc1.img_mapleIsland_maple_0_0-*.png"
DEFAULT_OUT = os.path.join(ROOT, "scripts", "launcher-art.zsh")
DEFAULT_WIDTH = 56
ALPHA_THRESHOLD = 128


def resolve_source(argv_source: str) -> str:
    if argv_source:
        return argv_source
    matches = sorted(glob.glob(os.path.join(ASSET_DIR, DEFAULT_PATTERN)))
    if not matches:
        raise SystemExit(f"找不到默认源图：{ASSET_DIR}/{DEFAULT_PATTERN}")
    return matches[0]


def cell_color(px) -> str | None:
    r, g, b, a = px
    if a < ALPHA_THRESHOLD:
        return None
    return f"{r};{g};{b}"


# 文本形式的转义前缀（写入 zsh 源码，运行时由 printf '%b' 解释）
ESC = "\\033["


def fg(color: str) -> str:
    return f"{ESC}38;2;{color}m"


def build_lines(image: Image.Image, width: int) -> list[str]:
    image = image.convert("RGBA")
    bbox = image.getbbox()
    if bbox:
        image = image.crop(bbox)
    img_w, img_h = image.size
    pixel_rows = max(2, round(img_h * width / img_w))
    small = image.resize((width, pixel_rows), Image.LANCZOS)
    pixels = small.load()

    lines: list[str] = []
    for y in range(0, pixel_rows - 1, 2):
        parts: list[str] = []
        for x in range(width):
            top = cell_color(pixels[x, y])
            bottom = cell_color(pixels[x, y + 1])
            if top is None and bottom is None:
                parts.append(" ")
                continue
            if top is None:  # 只有下半有内容 → 下半块
                parts.append(f"{fg(bottom)}▄{ESC}0m")
            elif bottom is None:  # 只有上半有内容 → 上半块
                parts.append(f"{fg(top)}▀{ESC}0m")
            else:  # 上下都有 → 上半块：前景=上，背景=下
                parts.append(f"{fg(top)}{ESC}48;2;{bottom}m▀{ESC}0m")
        # 去掉行尾多余空白（透明边距）
        line = "".join(parts).rstrip()
        if line:
            lines.append(line)
    # 收敛掉首尾全空行
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return lines


def zsh_quote(line: str) -> str:
    # 行内只会出现 \033 转义序列、Unicode 方块与空格，不会出现单引号
    assert "'" not in line
    return f" '{line}'"


def main() -> None:
    source = resolve_source(sys.argv[1] if len(sys.argv) > 1 else "")
    out_path = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUT
    width = int(sys.argv[3]) if len(sys.argv) > 3 else DEFAULT_WIDTH

    image = Image.open(source)
    lines = build_lines(image, width)
    if not lines:
        raise SystemExit("源图渲染结果为空")

    rel = os.path.relpath(source, ROOT)
    body = "\n".join(zsh_quote(line) for line in lines)
    content = f"""# Generated by scripts/gen_launcher_ascii_art.py -- 请勿手改；源图变化后重跑生成器即可。
# 源图：{rel}（{image.size[0]}x{image.size[1]}，{width} 列真彩半块像素画，共 {len(lines)} 行）
typeset -ga LAUNCHER_ART
LAUNCHER_ART=(
{body}
)
LAUNCHER_ART_COUNT=${{#LAUNCHER_ART[@]}}
typeset -gi LAUNCHER_ART_SHOWN=0
launcher_art_init() {{ LAUNCHER_ART_SHOWN=0 }}
# 用法：launcher_art_step 已完成阶段数 总阶段数
launcher_art_step() {{
  local target=$(( (LAUNCHER_ART_COUNT * ${{1:-0}} + ${{2:-1}} - 1) / ${{2:-1}} ))
  local i
  while (( LAUNCHER_ART_SHOWN < target )); do
    i=$(( LAUNCHER_ART_SHOWN + 1 ))
    printf '%b\\n' "${{LAUNCHER_ART[i]}}"
    LAUNCHER_ART_SHOWN=$i
  done
}}
launcher_art_finish() {{ launcher_art_step "$LAUNCHER_ART_COUNT" "$LAUNCHER_ART_COUNT" }}
"""
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"[ascii-art] {len(lines)} 行 -> {out_path}（源图 {rel}）")


if __name__ == "__main__":
    main()
